name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      MONGODB_DB_NAME: ${{ secrets.MONGODB_DB_NAME }}
      REDIS_URL: ${{ secrets.REDIS_URL }}
      REDIS_KEY_PREFIX: ${{ secrets.REDIS_KEY_PREFIX }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # - name: Run tests
      #   run: npm test

      - name: Build project
        run: npm run build
